apiVersion: v1
kind: Config
clusters:
- name: "your-cluster-name"
  cluster:
    server: "https://your-kubernetes-api-server-url"
    certificate-authority-data: "your-certificate-authority-data"
contexts:
- name: "your-context-name"
  context:
    cluster: "your-cluster-name"
    namespace: "your-kubernetes-namespace"
    user: "your-user-name"
current-context: "your-context-name"
users:
- name: "your-user-name"
  user:
    token: "your-service-account-token"
